baseURL = ""
languageCode = "en-us"
title = "Rancher Labs"
theme = "rancher-website-theme"
themesDir = "node_modules"
pluralizeListTitles = false

enableRobotsTXT = true
pygmentsCodeFences=true
pygmentsCodeFencesGuessSyntax=true


[permalinks]
  inside-pages = "/:filename/"

[params]
  addThis = "ra-5af1cc6793d86bfb"
  ### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
  ghdocsrepo = "https://github.com/rancher/docs"

[outputFormats.Search]
baseName = "search"
isPlaintext = true
mediaType = "application/json"
notAlternative = true

[outputs]
home = ["HTML", "RSS", "Search"]
page = ["HTML", "Search"]

[params.search]
vars = ["title","summary","date","publishdate","expirydate","permalink"]
params = ["categories","tags"]

[[menu.main]]
identifier = "what-is-rancher"
name       = "What is Rancher"
weight     = "1"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Overview"
  url        = "https://rancher.com/what-is-rancher/overview/"
  parent     = "what-is-rancher"
  weight     = "1"

  [[menu.main]]
  name       = "What Rancher Adds to Kubernetes"
  url        = "https://rancher.com/what-is-rancher/what-rancher-adds-to-kubernetes/"
  parent     = "what-is-rancher"
  weight     = "2"

  [[menu.main]]
  name       = "How is Rancher Different"
  url        = "https://rancher.com/what-is-rancher/how-is-rancher-different/"
  parent     = "what-is-rancher"
  weight     = "3"


  [[menu.main]]
  name       = "Run Kubernetes Anywhere"
  url        = "https://rancher.com//kubernetes/"
  parent     = "what-is-rancher"
  weight     = "4"

  [[menu.main]]
  # name       = "Cluster Operations"
  # url        = "https://rancher.com/what-is-rancher/cluster-operations/"
  # parent     = "what-is-rancher"
  # weight     = "5"

  [[menu.main]]
  # name       = "Hybrid cloud & multi-cloud"
  # url        = "https://rancher.com/what-is-rancher/hybrid-multi-cloud/"
  # parent     = "what-is-rancher"
  # weight     = "6"

  [[menu.main]]
  # name       = "Security & compliance"
  # url        = "https://rancher.com/what-is-rancher/security-and-compliance/"
  # parent     = "what-is-rancher"
  # weight     = "7"

  [[menu.main]]
  # name       = "Workload Management"
  # url        = "https://rancher.com/what-is-rancher/workload-management/"
  # parent     = "what-is-rancher"
  # weight     = "8"

  [[menu.main]]
  # name       = "100% Open Source"
  # url        = "https://rancher.com/what-is-rancher/open-source/"
  # parent     = "what-is-rancher"
  # weight     = "9"

  [[menu.main]]
  # name       = "How is Rancher Built"
  # url        = "https://rancher.com/what-is-rancher/how-is-rancher-built/"
  # parent     = "what-is-rancher"
  # weight     = "10"


[[menu.main]]
identifier = "products"
name       = "Products"
weight     = "2"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Rancher"
  url        = "https://rancher.com/what-is-rancher/overview/"
  parent     = "products"

  [[menu.main]]
  name       = "RancherOS"
  url        = "https://rancher.com/rancher-os/"
  parent     = "products"


[[menu.main]]
#identifier = "customers"
#name       = "Customers"
#url        = "https://rancher.com//customers/"
#weight     = "3"

[[menu.main]]
identifier = "learn"
name       = "Learn"
weight     = "4"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Blog"
  url        = "https://rancher.com/blog/"
  parent     = "learn"

  [[menu.main]]
  name       = "Rancher Docs"
  url        = "https://rancher.com/docs/"
  parent     = "learn"

  [[menu.main]]
  name       = "Training"
  url        = "https://rancher.com/training/"
  parent     = "learn"

  [[menu.main]]
  name       = "Forums"
  url        = "https://forums.rancher.com/"
  target = "_blank"
  pre        = "<i class='material-icons text-sm'>launch</i>"
  parent     = "learn"

  [[menu.main]]
  #name       = "Learning Resources"
  #url        = "https://rancher.com/learning-resources/"
  #parent     = "learn"

  [[menu.main]]
  name       = "Events"
  url        = "https://rancher.com/events/"
  parent     = "learn"


[[menu.main]]
identifier = "about"
name       = "About"
url        = "https://rancher.com/about/"
weight     = "5"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "News"
  url        = "https://rancher.com/news/"
  parent     = "about"

  [[menu.main]]
  name       = "About Us"
  url        = "https://rancher.com/about/"
  parent     = "about"

  [[menu.main]]
  name       = "Careers"
  url        = "https://rancher.com/careers/"
  parent     = "about"

  [[menu.main]]
  name       = "Contact Us"
  url        = "https://rancher.com/contact/"
  parent     = "about"

  [[menu.main]]
  name       = "Partners"
  url        = "https://rancher.com/partners/"
  parent     = "about"
